name: 'Laravel Pint'
description: 'Laravel Pint is an opinionated PHP code style fixer for minimalists.'
author: 'Agli Panci <agli.panci@gmail.com>'
inputs:
  testMode:
    description: "would you like to run Pint on test mode"
    required: false

  verboseMode:
    description: "would you like to run Pint on verbose mode"
    required: false

  configPath:
    description: "specify the custom config path"
    required: false

  preset:
    description: "pint preset"
    required: false

  onlyDirty:
    description: "only format changed files"
    required: false

  onlyDiff:
    description: "only format changed files that differ from the provided branch"
    required: false
    
  pintVersion:
    description: "laravel/pint composer version to install a specific version."
    required: false
   
  useComposer:
    description: "Use Laravel Pint version from project composer lock file. Lock file must be preset to use this flag."
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.test-mode }}
    - ${{ inputs.verbose-mode }}
    - ${{ inputs.config-path }}
    - ${{ inputs.preset }}
    - ${{ inputs.only-dirty }}
    - ${{ inputs.pint-version }}
    - ${{ inputs.use-composer }}
branding:
  icon: 'eye'  
  color: 'gray-dark'
